### ISSUE TITLE
Add an email whitelist command

### ISSUE THREAD

**Issue by ameihm0912** [mozilla-services/foxsec-pipeline-contrib#21]
Intent would be to add a new command (e.g., `whitelist_email`) that would operate the same way as the existing IP whitelisting.

**Comment by ameihm0912** [comment]
@ajvb this one seems pretty straightforward, I was wondering though do you think we should change the way the whitelist entries are stored/keyed so we can use the same namespace/kind for all entries regardless of type, which would keep things centralized?

Or would you prefer to keep them as different kinds? Or maybe different kinds in the same namespace?

Also, for this we would need to resolve https://bugzilla.mozilla.org/show_bug.cgi?id=1564951 before it is used.

**Comment by ajvb** [comment]
>I was wondering though do you think we should change the way the whitelist entries are stored/keyed so we can use the same namespace/kind for all entries regardless of type, which would keep things centralized?
>
>Or would you prefer to keep them as different kinds? Or maybe different kinds in the same namespace?

That's a good question. Since the whitelisted IP datastore entries have a namespace and kind of `whitelisted_ip`, I think it would be best to migrate to a new namespace (i.e. `whitelisted_object`) and separate them by kind. Separating them by kind could make the code simpler since you'd know what your specific query is going to return. But, I don't think it would make that big of a difference to have them in one namespace/kind combo.

**Comment by ameihm0912** [comment]
> I think it would be best to migrate to a new namespace (i.e. `whitelisted_object`) and separate them by kind.

👍
